# Generated by Django 4.0.4 on 2022-06-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_date',
            field=models.DateTimeField(default='', verbose_name='Todo Date'),
        ),
    ]
