# Generated by Django 4.0.4 on 2022-06-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_date',
            field=models.DateTimeField(default='2019-01-01 10:10', verbose_name='Todo Date'),
        ),
    ]
