# Generated by Django 4.0.4 on 2022-06-06 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_alter_actor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='nationality',
        ),
        migrations.AddField(
            model_name='actor',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='actor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
