# Generated by Django 4.0.4 on 2022-06-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0004_remove_actor_age_remove_actor_nationality_and_more'),
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Movie Name')),
                ('production_year', models.DateField(null=True, verbose_name='Production Year')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('actors', models.ManyToManyField(to='actor.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.director')),
            ],
        ),
    ]
