# Generated by Django 4.0.4 on 2022-06-06 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_remove_actor_age_remove_actor_nationality_and_more'),
        ('director', '0001_initial'),
        ('movie', '0002_remove_movie_actors_remove_movie_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='actor.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_year',
            field=models.DateField(null=True, verbose_name='Production Year'),
        ),
        migrations.AddField(
            model_name='movie',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
    ]
