# Generated by Django 4.0.4 on 2022-06-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_actors_movie_creation_time_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
